### ISSUE TITLE
ROS compiling alright，Roslauch alright , But the controls din't work

### ISSUE THREAD

**Issue by CosfilmTech** [ceinem/dji_rs2_ros_controller#1]
The device I use is Canable usbcan  
rostopic  echo  /receive messages   ： nothing coming from DJI RS2
rostopic  echo  /sent mesasages :  data is fine
rosservice call  /send_joint_cmd  and /send_joint_speed cmd :  DJI RS2 no respose
What could be the problem？

___________________________________________

Solved!
My Canable usbcan device driver problem.

**Comment by ceinem** [comment]
good to hear it's solved. CAN is tricky.
